---
- name: Executing Terraform
  terraform:
    project_path: '{{ playbook_dir }}/terraform-scripts/providers/{{provider}}'
    #plan_file: '{{ playbook_dir }}/terraform_scripts/providers/{{provider}}/tfplan'
    lock: true
    force_init: yes
    state: "{{tf_state}}"
    variables:
      instance_name: "{{instance_name}}"
  register: tf_output

- name: Print Outputs
  debug:
    var: tf_output

- name: Creating the Infra
  add_host:
    name: "{{instance_name}}"
    groups: just_created
    ansible_user: root
  when: tf_state == "present"

- debug:
    msg: "Printing an Ansible variable {{ inventory_hostname }} and a Terraform variable  {{instance_name}}"
  when: tf_state == "present"
