---
- name:           plan
  terraform:
    project_path: '{{ playbook_dir }}/terraform_scripts/providers/{{provider}}'
    #plan_file:    '{{ playbook_dir }}/terraform_scripts/providers/docker/tfplan'
    lock:         true
    force_init: no
    state:        "{{tf_state}}"
  register: tf_output

- name:           output
  debug:
    var: tf_output


# - name:           apply
#   terraform:
#     project_path: '{{ playbook_dir }}/terraform_scripts/providers/docker'
#     lock:         true
#     state:        present
#
# - name:           destroy
#   terraform:
#     project_path: '{{ playbook_dir }}/terraform_scripts/providers/docker'
#     lock:         true
#     state:        absent
