---
- name:           plan
  terraform:
    project_path: '{{ playbook_dir }}/terraform_scripts/providers/{{provider}}'
    lock:         true
    force_init: no
    state:        "{{tf_state}}"
  register: tf_output

- name:           output
  debug:
    var: tf_output
