---
- name: terraform is executed
  terraform:
    project_path: '{{ playbook_dir }}/terraform_scripts/providers/{{provider}}'
    #plan_file: '{{ playbook_dir }}/terraform_scripts/providers/docker/tfplan'
    lock: true
    force_init: yes
    state: "{{tf_state}}"
    variables:
      instance_name: "{{instance_name}}"
  register: tf_output

- name: output
  debug:
    var: tf_output

- name: new host added
  add_host:
    name: "{{ tf_output.outputs.public_dns.value }}"
    groups: just_created
    ansible_user: admin
  when: tf_state == "present"
